cmake_minimum_required(VERSION 3.14 FATAL_ERROR)

SET(APP_COMPONENTS  BLE Filter AudioProcess Opus) #FILE NAME

SET(APP_PATH ${CMAKE_CURRENT_SOURCE_DIR}/Application)
INCLUDE_DIRECTORIES(${APP_PATH}/Include)

IF(NOT APPLICATION_FIND_COMPONENTS)
    SET(APPLICATION_FIND_COMPONENTS ${APP_COMPONENTS})
    MESSAGE(FATAL_ERROR "No Application components selected,list of available modules: ${APPLICATION_FIND_COMPONENTS}")
ENDIF()

FOREACH(cmp ${APPLICATION_FIND_COMPONENTS})
    LIST(FIND APP_COMPONENTS ${cmp} APP_FOUND_INDEX)
    IF(${APP_FOUND_INDEX} LESS 0)
        LIST(APPEND APP_NOT_FIND_COMPONENTS ${cmp})
         MESSAGE (FATAL_ERROR  "NOT FOUND FOLLOWING APPLICATION SOURCES: ${APP_NOT_FIND_COMPONENTS}")
    ENDIF()
ENDFOREACH()

FOREACH(_CMP_LIST ${APPLICATION_FIND_COMPONENTS})
add_subdirectory(${APP_PATH}/${_CMP_LIST})
ENDFOREACH()

FOREACH (SRC_EACH_FILE ${USER_SOURCES})
# message("${SRC_EACH_FILE}")
GET_FILENAME_COMPONENT(_SOURCES_PATH ${SRC_EACH_FILE} DIRECTORY)
FOREACH(_CMP_LIST ${APPLICATION_FIND_COMPONENTS})
SET (_MODULE_PATH "${APP_PATH}/${_CMP_LIST}")
IF(${_SOURCES_PATH} MATCHES ${_MODULE_PATH})
LIST (APPEND APP_SRC ${SRC_EACH_FILE})
ENDIF()
ENDFOREACH()
ENDFOREACH()
LIST(REMOVE_DUPLICATES APP_SRC)
MESSAGE (STATUS  "All Selected module source found: ${APPLICATION_FIND_COMPONENTS}")

LIST(APPEND APP_SRC "${APP_PATH}/main.cpp") #update this if main file name is change