
SET(CMSIS_COMMON_HEADERS
core_cm4.h
)




SET(CMSIS_DEVICE_HEADERS stm32wb5mxx.h system_stm32wbxx.h)


FIND_PATH(CMSIS_COMMON_INCLUDE_DIR ${CMSIS_COMMON_HEADERS}
PATH_SUFFIXES include stm32${STM32_FAMILY_LOWER} cmsis
PATHS ${STM32Cube_DIR}/Drivers/CMSIS/Include/
CMAKE_FIND_ROOT_PATH_BOTH
)




FIND_PATH(CMSIS_DEVICE_INCLUDE_DIR ${CMSIS_DEVICE_HEADERS}
    PATH_SUFFIXES include stm32${STM32_FAMILY_LOWER} cmsis
    PATHS ${STM32Cube_DIR}/Drivers/CMSIS/Device/ST/STM32${STM32_FAMILY}xx/Include
    CMAKE_FIND_ROOT_PATH_BOTH
)

SET(CMSIS_INCLUDE_DIRS
${CMSIS_DEVICE_INCLUDE_DIR}
${CMSIS_COMMON_INCLUDE_DIR}
)
INCLUDE_DIRECTORIES(${CMSIS_INCLUDE_DIRS})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CMSIS DEFAULT_MSG CMSIS_INCLUDE_DIRS )      