
SET(DSP_COMMON_HEADERS
arm_math.h
)

# SET(DSP_LIBRARY
# 	libarm_cortexM4lf_math.a
# )

FIND_PATH(DSP_COMMON_INCLUDE_DIR ${DSP_COMMON_HEADERS}
# PATH_SUFFIXES include stm32${STM32_FAMILY_LOWER} cmsis
PATHS ${STM32Cube_DIR}/Drivers/DSP/Inc/
CMAKE_FIND_ROOT_PATH_BOTH
)


SET(DSP_INCLUDE_DIRS
${DSP_COMMON_INCLUDE_DIR}
)
INCLUDE_DIRECTORIES(${DSP_INCLUDE_DIRS})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DSP DEFAULT_MSG DSP_INCLUDE_DIRS )      